#! /usr/bin/env python
import sys
import requests
import json

url = sys.argv[1]

payload = dict(firstname='Minh', lastname = 'Pham')
r = requests.post(url, data=payload)

print r.request.headers
print 'Body: %s' % (repr(r.request.body),)
print r.status_code
print r.text


